// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAka8efpiespE3PlZEZmMpLFvPYKZGvniY',
    appId: '1:347404036368:web:2e24192924964e54115d95',
    messagingSenderId: '347404036368',
    projectId: 'blue-collar-8954a',
    authDomain: 'blue-collar-8954a.firebaseapp.com',
    storageBucket: 'blue-collar-8954a.appspot.com',
    measurementId: 'G-G0CCQ13RQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDma9sFUV8UbJ_LdHh3Ueauqhe8aKJNgLo',
    appId: '1:347404036368:android:54ac9752ec6c5c74115d95',
    messagingSenderId: '347404036368',
    projectId: 'blue-collar-8954a',
    storageBucket: 'blue-collar-8954a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMeXQJJiOiHvwBI6HGyRmXOX9UJ_Hy6aM',
    appId: '1:347404036368:ios:a5f4d1a5d5f84178115d95',
    messagingSenderId: '347404036368',
    projectId: 'blue-collar-8954a',
    storageBucket: 'blue-collar-8954a.appspot.com',
    iosBundleId: 'com.bluecollarng.blueCollarApp',
  );
}
